// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCSendMsgClient is the client API for GRPCSendMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCSendMsgClient interface {
	SendMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error)
}

type gRPCSendMsgClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCSendMsgClient(cc grpc.ClientConnInterface) GRPCSendMsgClient {
	return &gRPCSendMsgClient{cc}
}

func (c *gRPCSendMsgClient) SendMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, "/protoc.GRPCSendMsg/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCSendMsgServer is the server API for GRPCSendMsg service.
// All implementations must embed UnimplementedGRPCSendMsgServer
// for forward compatibility
type GRPCSendMsgServer interface {
	SendMsg(context.Context, *MessageRequest) (*MessageReply, error)
	mustEmbedUnimplementedGRPCSendMsgServer()
}

// UnimplementedGRPCSendMsgServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCSendMsgServer struct {
}

func (UnimplementedGRPCSendMsgServer) SendMsg(context.Context, *MessageRequest) (*MessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedGRPCSendMsgServer) mustEmbedUnimplementedGRPCSendMsgServer() {}

// UnsafeGRPCSendMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCSendMsgServer will
// result in compilation errors.
type UnsafeGRPCSendMsgServer interface {
	mustEmbedUnimplementedGRPCSendMsgServer()
}

func RegisterGRPCSendMsgServer(s grpc.ServiceRegistrar, srv GRPCSendMsgServer) {
	s.RegisterService(&GRPCSendMsg_ServiceDesc, srv)
}

func _GRPCSendMsg_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCSendMsgServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.GRPCSendMsg/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCSendMsgServer).SendMsg(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCSendMsg_ServiceDesc is the grpc.ServiceDesc for GRPCSendMsg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCSendMsg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.GRPCSendMsg",
	HandlerType: (*GRPCSendMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _GRPCSendMsg_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
