// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcSendMsgClient is the client API for GrpcSendMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcSendMsgClient interface {
	SendMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error)
}

type grpcSendMsgClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcSendMsgClient(cc grpc.ClientConnInterface) GrpcSendMsgClient {
	return &grpcSendMsgClient{cc}
}

func (c *grpcSendMsgClient) SendMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, "/proto.grpcSendMsg/sendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcSendMsgServer is the server API for GrpcSendMsg service.
// All implementations must embed UnimplementedGrpcSendMsgServer
// for forward compatibility
type GrpcSendMsgServer interface {
	SendMsg(context.Context, *MessageRequest) (*MessageReply, error)
	mustEmbedUnimplementedGrpcSendMsgServer()
}

// UnimplementedGrpcSendMsgServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcSendMsgServer struct {
}

func (UnimplementedGrpcSendMsgServer) SendMsg(context.Context, *MessageRequest) (*MessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedGrpcSendMsgServer) mustEmbedUnimplementedGrpcSendMsgServer() {}

// UnsafeGrpcSendMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcSendMsgServer will
// result in compilation errors.
type UnsafeGrpcSendMsgServer interface {
	mustEmbedUnimplementedGrpcSendMsgServer()
}

func RegisterGrpcSendMsgServer(s grpc.ServiceRegistrar, srv GrpcSendMsgServer) {
	s.RegisterService(&GrpcSendMsg_ServiceDesc, srv)
}

func _GrpcSendMsg_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcSendMsgServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.grpcSendMsg/sendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcSendMsgServer).SendMsg(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcSendMsg_ServiceDesc is the grpc.ServiceDesc for GrpcSendMsg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcSendMsg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.grpcSendMsg",
	HandlerType: (*GrpcSendMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendMsg",
			Handler:    _GrpcSendMsg_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
