// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package streamProtoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeSaFileServiceClient is the client API for SeSaFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeSaFileServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (SeSaFileService_UploadClient, error)
}

type seSaFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeSaFileServiceClient(cc grpc.ClientConnInterface) SeSaFileServiceClient {
	return &seSaFileServiceClient{cc}
}

func (c *seSaFileServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (SeSaFileService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &SeSaFileService_ServiceDesc.Streams[0], "/streamProtoc.SeSaFileService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &seSaFileServiceUploadClient{stream}
	return x, nil
}

type SeSaFileService_UploadClient interface {
	Send(*UploadRequest) error
	Recv() (*UploadResponse, error)
	grpc.ClientStream
}

type seSaFileServiceUploadClient struct {
	grpc.ClientStream
}

func (x *seSaFileServiceUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *seSaFileServiceUploadClient) Recv() (*UploadResponse, error) {
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SeSaFileServiceServer is the server API for SeSaFileService service.
// All implementations must embed UnimplementedSeSaFileServiceServer
// for forward compatibility
type SeSaFileServiceServer interface {
	Upload(SeSaFileService_UploadServer) error
	mustEmbedUnimplementedSeSaFileServiceServer()
}

// UnimplementedSeSaFileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeSaFileServiceServer struct {
}

func (UnimplementedSeSaFileServiceServer) Upload(SeSaFileService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedSeSaFileServiceServer) mustEmbedUnimplementedSeSaFileServiceServer() {}

// UnsafeSeSaFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeSaFileServiceServer will
// result in compilation errors.
type UnsafeSeSaFileServiceServer interface {
	mustEmbedUnimplementedSeSaFileServiceServer()
}

func RegisterSeSaFileServiceServer(s grpc.ServiceRegistrar, srv SeSaFileServiceServer) {
	s.RegisterService(&SeSaFileService_ServiceDesc, srv)
}

func _SeSaFileService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SeSaFileServiceServer).Upload(&seSaFileServiceUploadServer{stream})
}

type SeSaFileService_UploadServer interface {
	Send(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type seSaFileServiceUploadServer struct {
	grpc.ServerStream
}

func (x *seSaFileServiceUploadServer) Send(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *seSaFileServiceUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SeSaFileService_ServiceDesc is the grpc.ServiceDesc for SeSaFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeSaFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamProtoc.SeSaFileService",
	HandlerType: (*SeSaFileServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _SeSaFileService_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gRPC/streamProtoc/streamProtoc.proto",
}
